// LEVEL 1 - "Intake Station"
// The map is drawn as text. Each character in `map` is one 2x2 metre square.
// `things` is a second layer of the same size that places the player,
// monsters and items. See ../legend.js for what every character means.

export default {
  id: 'intake',
  name: 'Intake Station',
  subtitle: 'Sector 1 - Erebus Mining Colony',
  music: 'intake',
  parTime: 240,
  fog: { color: 0x0a0604, near: 3, far: 34 },
  playerAngle: 0,       // 0 = facing north (up the map)
  defaultWall: '#',
  legend: {
    // floors
    '.': { floor: 0, ceil: 3, light: 0.8, floorTex: 'floor_tile', ceilTex: 'ceil_panel' },
    'l': { floor: 0, ceil: 3.2, light: 1.0, floorTex: 'floor_tile', ceilTex: 'ceil_light' },
    ',': { floor: 0, ceil: 3, light: 0.5, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
    ';': { floor: 0, ceil: 3, light: 0.55, floorTex: 'floor_grate', ceilTex: 'ceil_panel', secret: true },
    ':': { floor: 0, ceil: 4.5, light: 0.72, floorTex: 'floor_hub', ceilTex: 'ceil_panel' },
    'm': { floor: 0, ceil: 4.0, light: 1.0, floorTex: 'floor_hub', ceilTex: 'ceil_light' },
    '_': { floor: 0, ceil: 9, light: 0.9, floorTex: 'floor_dirt', sky: true },
    '^': { floor: 1.0, ceil: 9, light: 0.95, floorTex: 'floor_plate', sky: true, lowerTex: 'support' },
    '3': { floor: 0.75, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '2': { floor: 0.5, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '1': { floor: 0.25, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    's': { floor: 0, ceil: 5, light: 0.5, floorTex: 'floor_concrete', ceilTex: 'ceil_panel' },
    'H': { floor: 2.0, ceil: 5, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel', lowerTex: 'support' },
    'L': { floor: 0, ceil: 5, light: 0.6, floorTex: 'floor_lift', lift: { low: 0, high: 2.0 } },
    'e': { floor: 0, ceil: 3, light: 0.75, floorTex: 'floor_tile', ceilTex: 'ceil_panel' },
    'X': { floor: 0, ceil: 3, light: 1.0, floorTex: 'exit', ceilTex: 'ceil_light', exit: true },
    '=': { floor: -0.5, ceil: 4, light: 0.75, floorTex: 'slime', ceilTex: 'ceil_rock', hazard: 10, lowerTex: 'brick' },
    'w': { floor: 0, ceil: 4, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_rock', lowerTex: 'support' },
    // walls
    '#': { wall: 'metal' },
    'T': { wall: 'tech' },
    '%': { wall: 'brick' },
    'P': { wall: 'support' },
    'C': { wall: 'crate' },
    // doors (the square the door sits in uses the listed floor/ceiling)
    'D': { door: {}, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'R': { door: { key: 'red' }, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'B': { door: { key: 'blue' }, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'S': { door: { secret: true, tex: 'metal' }, floor: 0, ceil: 3, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
    '$': { door: { secret: true, tex: 'brick' }, floor: 0, ceil: 4, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_rock' },
    // the entrance lobby where you start (recreated from a real room)
    'O': { floor: 0, ceil: 4.2, light: 0.5, floorTex: 'floor_lobby', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'c': { floor: 0, ceil: 4.2, light: 0.5, floorTex: 'carpet', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'n': { floor: 0, ceil: 4.2, light: 0.5, floorTex: 'floor_mat', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'u': { floor: 0, ceil: 3, light: 0.4, floorTex: 'carpet', ceilTex: 'ceil_office', upperTex: 'plaster_white' },
    'Y': { wall: 'plaster' },
    'Z': { wall: 'plaster_white' },
    'K': { wall: 'cork' },
    'G': { wall: 'glass' },
    'W': { door: { tex: 'door_wood' }, floor: 0, ceil: 2.4, light: 0.55, floorTex: 'floor_lobby', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'Q': { door: { secret: true, tex: 'plaster_white' }, floor: 0, ceil: 3, light: 0.5, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
  },
  // Lights and furniture for the entrance lobby (x / z in metres; see world/Props.js).
  lights: [
    ...[9, 13.8, 18.5].flatMap(x => [64.5, 69, 73.5].map(z => ({ x, y: 3.25, z, color: [1, 0.92, 0.8], i: 0.8, r: 8 }))),
    { x: 13, y: 2.85, z: 62.4, color: [0.3, 1, 0.5], i: 0.35, r: 3 },
    { x: 25, y: 2.7, z: 66, color: [0.88, 0.94, 1], i: 0.7, r: 7 },
    { x: 25, y: 2.7, z: 70, color: [0.88, 0.94, 1], i: 0.7, r: 7 },
    { x: 29.2, y: 1.8, z: 67, color: [0.45, 0.65, 1], i: 0.8, r: 6 },
  ],
  props: [
    // security desk along the cork wall, with its curved end
    ['deskRun', 9.0, 66.7, 90, { len: 6.6 }],
    ['deskCurve', 7.0, 70.0, 0, { r: 2, from: 0, to: 1.25 }],
    ['officeChair', 8.0, 65.0, 90], ['officeChair', 8.0, 68.6, 70],
    ['monitor', 9.05, 64.2, -90, { y: 0.78, feed: 0 }], ['monitor', 9.05, 65.0, -90, { y: 0.78, feed: null }],
    ['monitor', 9.05, 67.8, -90, { y: 0.78, feed: 3 }], ['monitor', 9.05, 68.6, -90, { y: 0.78, feed: 5, w: 0.5, h: 0.3 }],
    ['keyboard', 8.75, 64.6, -90, { y: 0.78 }], ['keyboard', 8.75, 68.2, -90, { y: 0.78 }],
    ['papers', 9.1, 69.4, 0, { y: 0.78 }],
    ['wallSign', 6.0, 66.6, 90, { y: 2.3, w: 3.4, h: 0.92 }],
    // north wall: TV, exit sign over the door, artwork
    ['tv', 9.0, 62.0, 0, { y: 2.0 }],
    ['exitSign', 13.0, 62.0, 0, { y: 2.85 }],
    ['frame', 16.6, 62.0, 0, { y: 1.7, w: 0.7, h: 0.9, art: 'violet' }],
    // seating by the glass front
    ['plant', 19.3, 75.3, 0], ['plant', 6.9, 75.2, 0, { h: 1.6 }],
    ['armchair', 18.8, 72.6, -90], ['armchair', 17.1, 75.1, 180], ['sideTable', 18.6, 74.6, 0],
    // wooden bench, slatted screen and prints on the east wall
    ['bench', 19.7, 64.4, -90, { len: 2.2 }],
    ['slatScreen', 19.3, 66.0, 0, { len: 1.4 }],
    ['frame', 20.0, 63.9, -90, { y: 1.75, w: 0.7, h: 0.5, art: 'print' }],
    ['frame', 20.0, 64.9, -90, { y: 1.75, w: 0.7, h: 0.5, art: 'print' }],
    ['tv', 20.0, 71.5, -90, { y: 2.0 }],
    ['detectorArch', 16.2, 67.5, 0],
    // exposed services and pendant lights in the ceiling
    ['duct', 11.0, 69.0, 90, { len: 14, y: 3.75, r: 0.22 }],
    ['duct', 16.5, 69.0, 90, { len: 14, y: 3.88, r: 0.15 }],
    ['duct', 13.0, 64.5, 0, { len: 14, y: 3.5, r: 0.12 }],
    ...[9, 13.8, 18.5].flatMap(x => [64.5, 69, 73.5].map(z => ['pendant', x, z, 0, { y: 4.2, drop: 0.7 }])),
    // control room: video wall and two operator desks
    ['videoWall', 30.0, 67.0, -90, { y: 1.75 }],
    ['officeDesk', 27.6, 66.2, 90], ['officeDesk', 27.6, 69.4, 90],
    ['monitor', 27.8, 65.8, -90, { y: 0.76, feed: 1 }], ['monitor', 27.8, 66.6, -90, { y: 0.76, feed: 2 }],
    ['monitor', 27.8, 69.0, -90, { y: 0.76, feed: 6 }], ['monitor', 27.8, 69.8, -90, { y: 0.76, feed: 7 }],
    ['keyboard', 27.4, 66.2, -90, { y: 0.76 }], ['keyboard', 27.4, 69.4, -90, { y: 0.76 }],
    ['officeChair', 26.6, 66.2, 90, { seat: 0xc8c4b8 }], ['officeChair', 26.6, 69.4, 90, { seat: 0xc8c4b8 }],
    ['pcTower', 28.1, 67.4, 0], ['bin', 28.1, 70.6, 0],
  ],
  // extra collision for shapes that aren't simple boxes: [x, z, halfWidth, halfDepth]
  colliders: [
    [8.91, 70.59, 0.3, 0.3], [8.53, 71.29, 0.3, 0.3], [7.9, 71.78, 0.3, 0.3],
    [15.7, 67.5, 0.06, 0.28], [16.7, 67.5, 0.06, 0.28],
  ],
  map: [
  '############%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       ',
  '#HHHHsssssss%_____________________________%       ',
  '#HHHHsssCCss%_____________________________%TTTTTTT',
  '#HHHHsssCsss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHsssssss%___P_______^^^^^^^______P____%eeeeeeT',
  '#HHHHLssssss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHLssssssR___________^^^^^^^___________BeeeeXXT',
  '#HHHHsssssss%___________^^^^^^^___________%eeeeXXT',
  '#HHHHsssssss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHsssssss%___P_________333________P____%eeeeeeT',
  '#HHHHssssCCs%_____________222_____________%eeeeeeT',
  '#HHHHsssssss%_____________111_____________%TTTTTTT',
  '#HHHHsssssss%_____________________________%       ',
  '############%%%%%%%#,,,#%%%%%%%%%%%%%%%D%%%       ',
  '                   #,,,#             #,,,#        ',
  '                   #,,,#             #,,,#        ',
  '              TTTTTTTDTTTTTTT        #,,,#        ',
  '              T:::::::::::::T%%%%%%%%%%D%%%%%%%   ',
  '              T:::::::::::::T==========ww=====%   ',
  '              T:::::::::::::T=========wwwww===%   ',
  '              T:::P:::::P:::T=========wwwww===%   ',
  '    ###########:::::mmm:::::T=========wwwww===%   ',
  '    #,,,,,,,,,#:::::mmm:::::Dwwwwwwwwwwwwww===%   ',
  '    #,,,,,,,,,D:::::mmm:::::Twwwwwwwwwwwwww===%   ',
  '    #,,,,,,,,,#:::P:::::P:::T=========wwwww===%%%%',
  '    #,,,#######:::::::::::::T=========wwwww=ww%;;%',
  '    #,,,#     T:::::::::::::T===============ww$;;%',
  '    #,,,#     T:::::::::::::T===============ww%;;%',
  '    #,,,#     TTTTTTTTTTTTTTT=================%%%%',
  '    #,,,#                   %=================%   ',
  '  YYYYWYYYY                                       ',
  '  KccOOOOOYYYYYY                                  ',
  '  KccOOOOOYuuuuZ                                  ',
  '  KccOOOOOWuuuuZYYYY                              ',
  '  KccOOOOOYuuuuZ;;;Y                              ',
  '  KccOOOOOYuuuuQ;;;Y                              ',
  '  KccOOOOOYZZZZZ;;;Y                              ',
  '  KOOnnnOOY    YYYYY                              ',
  '  YGGGGGGGY                                       ',
  ],
  things: [
    '                                                  ',
    ' b........e. .............................        ',
    ' .......  .. ..s........................g.        ',
    ' .s..... ... ...........i.....i..h........ ...... ',
    ' ........h.. ... ...f................ .... e.r... ',
    ' ........... ............r................ ...z.. ',
    ' ..3....z... .....h........R.......o...... .g.... ',
    ' ........... ................r............ +..... ',
    ' ......r.... ...........i.....i...f....... ...... ',
    ' ........... ... ..........d......... .... ..r... ',
    ' .U......  . ..............d.......h...... ...... ',
    ' ......+..h. .oo....h......d...........s..        ',
    ' ........... .............e.............+.        ',
    '                    ...                           ',
    '                    .b.               ...         ',
    '                    ...               .+.         ',
    '                                      ...         ',
    '               +..........o.                      ',
    '               ..h.......h.. .................    ',
    '               ............. ...h.............    ',
    '               ... ..... ... ............s....    ',
    '               ............. .................    ',
    '     ......... ............. .....h...e.2.....    ',
    '     .....h.h. ............. .................    ',
    '     ......... ... ..... ... ..........r......    ',
    '     ...       ............. ................. .. ',
    '     .b.       .o...h...z.r. ................. v. ',
    '     ...       ............b ................. .. ',
    '     ...                     .................    ',
    '     ...                     .................    ',
    '                                                  ',
    '                                                  ',
    '   .....    b                                     ',
    '   ..+..                                          ',
    '   ..... ....  ..e                                ',
    '   ..... ....  ..a                                ',
    '   ...p.                                          ',
    '   .......                                        ',
    '                                                  ',
  ],
};
