// LEVEL 1 - "Intake Station"
// The map is drawn as text. Each character in `map` is one 2x2 metre square.
// `things` is a second layer of the same size that places the player,
// monsters and items. See ../legend.js for what every character means.

export default {
  id: 'intake',
  name: 'Intake Station',
  subtitle: 'Sector 1 - Erebus Mining Colony',
  music: 'intake',
  parTime: 240,
  fog: { color: 0x0a0604, near: 3, far: 34 },
  playerAngle: 0,       // 0 = facing north (up the map)
  defaultWall: '#',
  legend: {
    // floors
    '.': { floor: 0, ceil: 3, light: 0.8, floorTex: 'floor_tile', ceilTex: 'ceil_panel' },
    'l': { floor: 0, ceil: 3.2, light: 1.0, floorTex: 'floor_tile', ceilTex: 'ceil_light' },
    ',': { floor: 0, ceil: 3, light: 0.5, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
    ';': { floor: 0, ceil: 3, light: 0.55, floorTex: 'floor_grate', ceilTex: 'ceil_panel', secret: true },
    ':': { floor: 0, ceil: 4.5, light: 0.72, floorTex: 'floor_hub', ceilTex: 'ceil_panel' },
    'm': { floor: 0, ceil: 4.0, light: 1.0, floorTex: 'floor_hub', ceilTex: 'ceil_light' },
    '_': { floor: 0, ceil: 9, light: 0.9, floorTex: 'floor_dirt', sky: true },
    '^': { floor: 1.0, ceil: 9, light: 0.95, floorTex: 'floor_plate', sky: true, lowerTex: 'support' },
    '3': { floor: 0.75, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '2': { floor: 0.5, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '1': { floor: 0.25, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    's': { floor: 0, ceil: 5, light: 0.5, floorTex: 'floor_concrete', ceilTex: 'ceil_panel' },
    'H': { floor: 2.0, ceil: 5, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel', lowerTex: 'support' },
    'L': { floor: 0, ceil: 5, light: 0.6, floorTex: 'floor_lift', lift: { low: 0, high: 2.0 } },
    'e': { floor: 0, ceil: 3, light: 0.75, floorTex: 'floor_tile', ceilTex: 'ceil_panel' },
    'X': { floor: 0, ceil: 3, light: 1.0, floorTex: 'exit', ceilTex: 'ceil_light', exit: true },
    '=': { floor: -0.5, ceil: 4, light: 0.75, floorTex: 'slime', ceilTex: 'ceil_rock', hazard: 10, lowerTex: 'brick' },
    'w': { floor: 0, ceil: 4, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_rock', lowerTex: 'support' },
    // walls
    '#': { wall: 'metal' },
    'T': { wall: 'tech' },
    '%': { wall: 'brick' },
    'P': { wall: 'support' },
    'C': { wall: 'crate' },
    // doors (the square the door sits in uses the listed floor/ceiling)
    'D': { door: {}, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'R': { door: { key: 'red' }, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'B': { door: { key: 'blue' }, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'S': { door: { secret: true, tex: 'metal' }, floor: 0, ceil: 3, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
    '$': { door: { secret: true, tex: 'brick' }, floor: 0, ceil: 4, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_rock' },
  },
  map: [
  '############%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       ',
  '#HHHHsssssss%_____________________________%       ',
  '#HHHHsssCCss%_____________________________%TTTTTTT',
  '#HHHHsssCsss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHsssssss%___P_______^^^^^^^______P____%eeeeeeT',
  '#HHHHLssssss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHLssssssR___________^^^^^^^___________BeeeeXXT',
  '#HHHHsssssss%___________^^^^^^^___________%eeeeXXT',
  '#HHHHsssssss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHsssssss%___P_________333________P____%eeeeeeT',
  '#HHHHssssCCs%_____________222_____________%eeeeeeT',
  '#HHHHsssssss%_____________111_____________%TTTTTTT',
  '#HHHHsssssss%_____________________________%       ',
  '############%%%%%%%#,,,#%%%%%%%%%%%%%%%D%%%       ',
  '                   #,,,#             #,,,#        ',
  '                   #,,,#             #,,,#        ',
  '              TTTTTTTDTTTTTTT        #,,,#        ',
  '              T:::::::::::::T%%%%%%%%%%D%%%%%%%   ',
  '              T:::::::::::::T==========ww=====%   ',
  '              T:::::::::::::T=========wwwww===%   ',
  '              T:::P:::::P:::T=========wwwww===%   ',
  '    ###########:::::mmm:::::T=========wwwww===%   ',
  '    #,,,,,,,,,#:::::mmm:::::Dwwwwwwwwwwwwww===%   ',
  '    #,,,,,,,,,D:::::mmm:::::Twwwwwwwwwwwwww===%   ',
  '    #,,,,,,,,,#:::P:::::P:::T=========wwwww===%%%%',
  '    #,,,#######:::::::::::::T=========wwwww=ww%;;%',
  '    #,,,#     T:::::::::::::T===============ww$;;%',
  '    #,,,#     T:::::::::::::T===============ww%;;%',
  '    #,,,#     TTTTTTTTTTTTTTT=================%%%%',
  '    #,,,#                   %=================%   ',
  '  ####D####                 %%%%%%%%%%%%%%%%%%%   ',
  '  #.......#                                       ',
  '  #.......#####                                   ',
  '  #..lll..#;;;#                                   ',
  '  #..lll..S;;;#                                   ',
  '  #..lll..#;;;#                                   ',
  '  #.......#####                                   ',
  '  #.......#                                       ',
  '  #########                                       ',
  ],
  things: [
  '                                                  ',
  ' b........e. .............................        ',
  ' .......  .. ..s........................g.        ',
  ' .s..... ... ...........i.....i..h........ ...... ',
  ' ........h.. ... .................... .... e.r... ',
  ' ........... ............r................ ...... ',
  ' ..3........ .....h........R.......o...... .g.... ',
  ' ........... ................r............ +..... ',
  ' ......r.... ...........i.....i........... ...... ',
  ' ........... ... ..........d......... .... ..r... ',
  ' .U......  . ..............d.......h...... ...... ',
  ' ......+..h. .oo....h......d...........s..        ',
  ' ........... .............e.............+.        ',
  '                    ...                           ',
  '                    .b.               ...         ',
  '                    ...               .+.         ',
  '                                      ...         ',
  '               +..........o.                      ',
  '               ..h.......h.. .................    ',
  '               ............. ...h.............    ',
  '               ... ..... ... ............s....    ',
  '               ............. .................    ',
  '     ......... ............. .....h...e.2.....    ',
  '     .....h.h. ............. .................    ',
  '     ......... ... ..... ... ..........r......    ',
  '     ...       ............. ................. .. ',
  '     .b.       .o...h.....r. ................. v. ',
  '     ...       ............b ................. .. ',
  '     ...                     .................    ',
  '     ...                     .................    ',
  '                                                  ',
  '   .......                                        ',
  '   .b...+.                                        ',
  '   ....... e..                                    ',
  '   ....... .a.                                    ',
  '   ....... ...                                    ',
  '   ...p...                                        ',
  '   .......                                        ',
  '                                                  ',
  ],
};
