// LEVEL 3 - "The Maw Gate"
// The breach itself. Arm up in the armoury, then face The Warden.
// The exit gate only works once the Warden is dead.

export default {
  id: 'mawgate',
  name: 'The Maw Gate',
  subtitle: 'Sector 3 - The Breach',
  music: 'boss',
  parTime: 240,
  exitRequiresBoss: true,
  fog: { color: 0x1c0402, near: 4, far: 46 },
  playerAngle: 0,
  defaultWall: '&',
  legend: {
    '.': { floor: 0, ceil: 3.4, light: 0.7, floorTex: 'floor_tile', ceilTex: 'ceil_rock' },
    'l': { floor: 0, ceil: 3.6, light: 1.0, floorTex: 'floor_tile', ceilTex: 'ceil_light' },
    ',': { floor: 0, ceil: 3, light: 0.45, floorTex: 'floor_grate', ceilTex: 'ceil_rock' },
    ';': { floor: 0, ceil: 3, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_rock', secret: true },
    'k': { floor: 0, ceil: 4, light: 0.55, floorTex: 'floor_concrete', ceilTex: 'ceil_rock' },
    'g': { floor: 0, ceil: 12, light: 0.85, floorTex: 'hellrock', sky: true },
    '~': { floor: -0.6, ceil: 12, light: 1.1, floorTex: 'lava', sky: true, hazard: 20, lowerTex: 'hellrock' },
    '^': { floor: 1.0, ceil: 12, light: 0.9, floorTex: 'floor_plate', sky: true, lowerTex: 'flesh' },
    '3': { floor: 0.75, ceil: 12, light: 0.9, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '2': { floor: 0.5, ceil: 12, light: 0.9, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '1': { floor: 0.25, ceil: 12, light: 0.9, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    'X': { floor: 1.0, ceil: 12, light: 1.1, floorTex: 'exit', sky: true, exit: true, lowerTex: 'flesh' },
    '&': { wall: 'hellrock' },
    '%': { wall: 'flesh' },
    'P': { wall: 'support' },
    'D': { door: {}, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_rock' },
    '$': { door: { secret: true, tex: 'flesh' }, floor: 0, ceil: 4, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_rock' },
  },
  map: [
    '                                        ',
    '                                        ',
    '    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&   ',
    '    &gggggggggggg^^^X^^^gggggggggggg&   ',
    '    &g~~~~~gggggg^^^^^^^gggggg~~~~~g&   ',
    '    &g~~~~~gggggg^^^^^^^gggggg~~~~~g&   ',
    '    &g~~~~~gggggggg333gggggggg~~~~~g&   ',
    '    &g~~~~~gggggggg222gggggggg~~~~~g&   ',
    '    &g~~~~~ggPggggg111gggggPgg~~~~~g&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &gggggggggggggggPggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggPgggggggggggggPgggggggg&   ',
    '    &g~~~~~ggggggggggggggggggg~~~~~g&   ',
    '    &g~~~~~ggggggggggggggggggg~~~~~g&   ',
    '    &g~~~~~ggggggggggggggggggg~~~~~g&   ',
    '    &g~~~~~ggggggggggggggggggg~~~~~g&   ',
    '    &g~~~~~ggggggggggggggggggg~~~~~g&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &ggggggggggggggggggggggggggggggg&   ',
    '    &&&&&&&&&&&&&&%%D%%&&&&&&&&&&&&&&   ',
    '%%%%%kkkkkkkkkkkkk%,,,%                 ',
    '%;;;%k~~~kkkkkkkkk%,,,%                 ',
    '%;;;$k~k~kkkkkkkkkD,,,%                 ',
    '%;;;%k~k~kkk~~~~~k%,,,%                 ',
    '%%%%%k~~~kkk~~~~~k%,,,%                 ',
    '    %kkkkkkk~~~~~k&&D&&&&&              ',
    '    %%%%%%%%%%%&.........&              ',
    '               &...lll...&              ',
    '               &...lll...&              ',
    '               &...lll...&              ',
    '               &.........&              ',
    '               &.........&              ',
    '               &&&&&&&&&&&              ',
  ],
  things: [
    '                                        ',
    '                                        ',
    '                                        ',
    '     K......t...............t......*    ',
    '     .......s...............s.......    ',
    '     ...............................    ',
    '     ...............................    ',
    '     ...............................    ',
    '     ........ ............. ........    ',
    '     ...............................    ',
    '     ...............................    ',
    '     ...............W...............    ',
    '     .......w...............w.......    ',
    '     C.............. ..............C    ',
    '     ...h...............x.......h...    ',
    '     ...............................    ',
    '     ...........x...................    ',
    '     ...............................    ',
    '     ........ ............. ........    ',
    '     ...............................    ',
    '     ...............................    ',
    '     ...............................    ',
    '     ..........h.........h..........    ',
    '     ...............................    ',
    '     .............o...o.............    ',
    '     +......t...............t......*    ',
    '                                        ',
    '     5...*g....Cs. ...                  ',
    ' K.. .........g... ..+                  ',
    ' .v. ......s...... .w.                  ',
    ' ..C ............. ...                  ',
    '     ............. ...                  ',
    '     K............                      ',
    '                .........               ',
    '                .K..E..C.               ',
    '                .........               ',
    '                .........               ',
    '                .*..p..A.               ',
    '                .........               ',
    '                                        ',
  ],
};
