// LEVEL 1 - "Intake Station"
// The map is drawn as text. Each character in `map` is one 2x2 metre square.
// `things` is a second layer of the same size that places the player,
// monsters and items. See ../legend.js for what every character means.

const LOBBY_LIGHTS = [[7.8, 63.8], [11.5, 63.8], [15.2, 63.8], [7.8, 67.8], [11.5, 67.2], [15.2, 67.2], [7.8, 71.8], [11.5, 70.8], [15.2, 70.8], [12.5, 73.3]];

export default {
  id: 'intake',
  name: 'Intake Station',
  subtitle: 'Sector 1 - Erebus Mining Colony',
  music: 'intake',
  parTime: 240,
  fog: { color: 0x0a0604, near: 3, far: 34 },
  playerAngle: 0,       // 0 = facing north (up the map)
  defaultWall: '#',
  legend: {
    // floors
    '.': { floor: 0, ceil: 3, light: 0.8, floorTex: 'floor_tile', ceilTex: 'ceil_panel' },
    'l': { floor: 0, ceil: 3.2, light: 1.0, floorTex: 'floor_tile', ceilTex: 'ceil_light' },
    ',': { floor: 0, ceil: 3, light: 0.5, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
    ';': { floor: 0, ceil: 3, light: 0.55, floorTex: 'floor_grate', ceilTex: 'ceil_panel', secret: true },
    ':': { floor: 0, ceil: 4.5, light: 0.72, floorTex: 'floor_hub', ceilTex: 'ceil_panel' },
    'm': { floor: 0, ceil: 4.0, light: 1.0, floorTex: 'floor_hub', ceilTex: 'ceil_light' },
    '_': { floor: 0, ceil: 9, light: 0.9, floorTex: 'floor_dirt', sky: true },
    '^': { floor: 1.0, ceil: 9, light: 0.95, floorTex: 'floor_plate', sky: true, lowerTex: 'support' },
    '3': { floor: 0.75, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '2': { floor: 0.5, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '1': { floor: 0.25, ceil: 9, light: 0.92, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    's': { floor: 0, ceil: 5, light: 0.5, floorTex: 'floor_concrete', ceilTex: 'ceil_panel' },
    'H': { floor: 2.0, ceil: 5, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel', lowerTex: 'support' },
    'L': { floor: 0, ceil: 5, light: 0.6, floorTex: 'floor_lift', lift: { low: 0, high: 2.0 } },
    'e': { floor: 0, ceil: 3, light: 0.75, floorTex: 'floor_tile', ceilTex: 'ceil_panel' },
    'X': { floor: 0, ceil: 3, light: 1.0, floorTex: 'exit', ceilTex: 'ceil_light', exit: true },
    '=': { floor: -0.5, ceil: 4, light: 0.75, floorTex: 'slime', ceilTex: 'ceil_rock', hazard: 10, lowerTex: 'brick' },
    'w': { floor: 0, ceil: 4, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_rock', lowerTex: 'support' },
    // walls
    '#': { wall: 'metal' },
    'T': { wall: 'tech' },
    '%': { wall: 'brick' },
    'P': { wall: 'support' },
    'C': { wall: 'crate' },
    // doors (the square the door sits in uses the listed floor/ceiling)
    'D': { door: {}, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'R': { door: { key: 'red' }, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'B': { door: { key: 'blue' }, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'S': { door: { secret: true, tex: 'metal' }, floor: 0, ceil: 3, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
    '$': { door: { secret: true, tex: 'brick' }, floor: 0, ceil: 4, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_rock' },
    // the entrance lobby where you start (recreated from a real room)
    'O': { floor: 0, ceil: 4.2, light: 0.5, floorTex: 'floor_lobby', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'c': { floor: 0, ceil: 4.2, light: 0.5, floorTex: 'carpet', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'n': { floor: 0, ceil: 4.2, light: 0.5, floorTex: 'floor_mat', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'u': { floor: 0, ceil: 3, light: 0.4, floorTex: 'carpet', ceilTex: 'ceil_office', upperTex: 'plaster_white' },
    'Y': { wall: 'plaster' },
    'Z': { wall: 'plaster_white' },
    'K': { wall: 'cork' },
    'G': { wall: 'glass' },
    'W': { door: { tex: 'door_wood' }, floor: 0, ceil: 2.4, light: 0.55, floorTex: 'floor_lobby', ceilTex: 'ceil_exposed', upperTex: 'plaster' },
    'Q': { door: { secret: true, tex: 'plaster_white' }, floor: 0, ceil: 3, light: 0.5, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
  },
  // Lights and furniture for the entrance lobby, laid out from photos of a real
  // room (x / z in metres; see world/Props.js). West: cork wall with the
  // security desk. North: plaques, TV, door, artwork. East: glass entrance.
  // North-west: nook with the security arch. South: the control room.
  lights: [
    ...LOBBY_LIGHTS.map(([x, z]) => ({ x, y: 3.3, z, color: [1, 0.93, 0.82], i: 0.62, r: 7.5 })),
    { x: 5, y: 3.3, z: 64, color: [1, 0.93, 0.82], i: 0.5, r: 5 },
    { x: 17.4, y: 2.9, z: 69.7, color: [0.3, 1, 0.5], i: 0.3, r: 3 },
    { x: 17, y: 1.5, z: 69.7, color: [0.55, 0.62, 0.8], i: 0.3, r: 5 },          // street light through the glass
    { x: 9, y: 2.7, z: 79, color: [0.88, 0.94, 1], i: 0.7, r: 7 },
    { x: 13, y: 2.7, z: 79, color: [0.88, 0.94, 1], i: 0.7, r: 7 },
    { x: 11, y: 1.8, z: 83.2, color: [0.45, 0.65, 1], i: 0.8, r: 6 },
  ],
  props: [
    // security desk: a plain run along the cork wall and a raised, curved counter at its north end
    ['deskRun', 9.2, 71.1, 90, { len: 3.8, plain: true }],
    ['deskCurve', 7.2, 69.2, 0, { r: 2, from: -1.3, to: 0 }],
    ['officeChair', 8.0, 70.4, 135],
    ['monitor', 8.78, 68.44, -64, { y: 0.78, feed: 0, w: 0.62, h: 0.38 }], ['monitor', 8.29, 67.83, -38, { y: 0.78, feed: null }],
    ['keyboard', 8.45, 68.75, -55, { y: 0.78 }], ['phone', 8.9, 69.3, -80, { y: 0.78 }],
    ['bottle', 8.95, 67.65, 0, { y: 0.78 }], ['mug', 9.3, 69.55, 0, { y: 0.78 }],
    ['mug', 9.35, 72.1, 0, { y: 0.78 }], ['bottle', 9.1, 72.35, 0, { y: 0.78, color: 0x2a2a2a }],
    ['papers', 9.2, 72.7, 90, { y: 0.78 }],
    ['panel', 6.0, 70.0, 90, { w: 8, h: 3.1 }],
    ['wallSign', 6.04, 69.6, 90, { y: 2.35, w: 3.6, h: 1.0 }],
    ['domeCam', 6.0, 67.2, 90, { y: 3.4 }],
    // north-west nook: security arch, slatted screens, wooden console, photo prints
    ['detectorArch', 5.3, 63.4, 90],
    ['slatScreen', 6.1, 65.45, 90, { len: 1.1, h: 2.9 }],
    ['slatScreen', 6.9, 62.45, 90, { len: 0.9, h: 2.9 }],
    ['bench', 4.35, 65.0, 90, { len: 1.2 }],
    ['frame', 4.0, 64.4, 90, { y: 1.85, w: 0.6, h: 0.45, art: 'print' }],
    ['frame', 4.0, 65.4, 90, { y: 1.85, w: 0.6, h: 0.45, art: 'print' }],
    // north wall: certificates, TV, the wooden door, artwork; armchairs and a plant in the corner
    ['plaques', 8.6, 62.0, 0, { y: 1.8 }],
    ['tv', 10.4, 62.0, 0, { y: 2.0 }],
    ['frame', 15.6, 62.0, 0, { y: 1.7, w: 0.72, h: 0.92, art: 'violet' }],
    ['armchair', 15.8, 62.75, 0], ['armchair', 17.1, 64.4, -80],
    ['plant', 17.35, 65.9, 0, { h: 2.4, broad: true }],
    // east wall: glass front with double doors and the exit sign
    ['glassFront', 17.98, 69.2, -90, { len: 9.4, doorAt: -0.5 }],
    ['exitSign', 18.0, 69.7, -90, { y: 2.95 }],
    // exposed ceiling: ducts, diffusers, air units, cable trays, downlights
    ['duct', 10.5, 68, 90, { len: 12, y: 3.72, r: 0.25 }],
    ['duct', 15.2, 68, 90, { len: 12, y: 3.9, r: 0.18 }],
    ['duct', 11, 64.6, 0, { len: 12, y: 3.5, r: 0.2 }],
    ['duct', 12, 72.4, 0, { len: 12, y: 3.6, r: 0.14 }],
    ['diffuser', 10.5, 66.4, 0, { y: 3.72, drop: 0.45 }], ['diffuser', 13.8, 64.6, 0, { y: 3.5, drop: 0.3 }],
    ['diffuser', 12.6, 72.4, 0, { y: 3.6, drop: 0.35 }], ['diffuser', 15.2, 69.8, 0, { y: 3.9, drop: 0.55 }],
    ['ceilingUnit', 8.2, 66.3, 0, { y: 4.2 }], ['ceilingUnit', 13.4, 68.2, 0, { y: 4.2 }], ['ceilingUnit', 8.4, 72.8, 0, { y: 4.2 }],
    ['cableTray', 12, 67.4, 0, { len: 12, y: 4.05 }], ['cableTray', 12.6, 68, 90, { len: 12, y: 4.0 }],
    ...LOBBY_LIGHTS.map(([x, z]) => ['pendant', x, z, 0, { y: 4.2, drop: 0.62 }]),
    ['pendant', 5, 64, 0, { y: 4.2, drop: 0.62 }],
    ['domeCam', 12.0, 74.0, 180, { y: 3.3 }],
    // control room (through the door in the south wall): video wall and two operator desks
    ['videoWall', 11.0, 84.0, 180, { y: 1.75 }],
    ['officeDesk', 9.4, 81.8, 0], ['officeDesk', 12.8, 81.8, 0],
    ['monitor', 9.0, 81.9, 180, { y: 0.76, feed: 1 }], ['monitor', 9.8, 81.9, 180, { y: 0.76, feed: 2 }],
    ['monitor', 12.4, 81.9, 180, { y: 0.76, feed: 6 }], ['monitor', 13.2, 81.9, 180, { y: 0.76, feed: 7 }],
    ['keyboard', 9.4, 81.5, 180, { y: 0.76 }], ['keyboard', 12.8, 81.5, 180, { y: 0.76 }],
    ['officeChair', 9.4, 80.6, 0, { seat: 0xc8c4b8 }], ['officeChair', 12.8, 80.6, 0, { seat: 0xc8c4b8 }],
    ['pcTower', 10.5, 82.2, 0], ['bin', 14.3, 82.6, 0],
  ],
  // extra collision for shapes that aren't simple boxes: [x, z, halfWidth, halfDepth]
  colliders: [
    [9.16, 68.8, 0.35, 0.35], [8.85, 68.07, 0.35, 0.35], [8.28, 67.52, 0.35, 0.35], [7.7, 67.3, 0.35, 0.35],
    [5.3, 62.9, 0.3, 0.06], [5.3, 63.9, 0.3, 0.06],
  ],
  map: [
  '############%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       ',
  '#HHHHsssssss%_____________________________%       ',
  '#HHHHsssCCss%_____________________________%TTTTTTT',
  '#HHHHsssCsss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHsssssss%___P_______^^^^^^^______P____%eeeeeeT',
  '#HHHHLssssss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHLssssssR___________^^^^^^^___________BeeeeXXT',
  '#HHHHsssssss%___________^^^^^^^___________%eeeeXXT',
  '#HHHHsssssss%___________^^^^^^^___________%eeeeeeT',
  '#HHHHsssssss%___P_________333________P____%eeeeeeT',
  '#HHHHssssCCs%_____________222_____________%eeeeeeT',
  '#HHHHsssssss%_____________111_____________%TTTTTTT',
  '#HHHHsssssss%_____________________________%       ',
  '############%%%%%%%#,,,#%%%%%%%%%%%%%%%D%%%       ',
  '                   #,,,#             #,,,#        ',
  '                   #,,,#             #,,,#        ',
  '              TTTTTTTDTTTTTTT        #,,,#        ',
  '              T:::::::::::::T%%%%%%%%%%D%%%%%%%   ',
  '              T:::::::::::::T==========ww=====%   ',
  '              T:::::::::::::T=========wwwww===%   ',
  '              T:::P:::::P:::T=========wwwww===%   ',
  '    ###########:::::mmm:::::T=========wwwww===%   ',
  '    #,,,,,,,,,#:::::mmm:::::Dwwwwwwwwwwwwww===%   ',
  '    #,,,,,,,,,D:::::mmm:::::Twwwwwwwwwwwwww===%   ',
  '    #,,,,,,,,,#:::P:::::P:::T=========wwwww===%%%%',
  '    #,,,#######:::::::::::::T=========wwwww=ww%;;%',
  '    #,,,#     T:::::::::::::T===============ww$;;%',
  '    #,,,#     T:::::::::::::T===============ww%;;%',
  '    #,,,#     TTTTTTTTTTTTTTT=================%%%%',
  '    #,,,#                   %=================%   ',
  ' YYYYYWYYY                  %%%%%%%%%%%%%%%%%%%   ',
  ' YOOOOOOOY                                        ',
  ' YOOOOOOOY                                        ',
  '  YccOOnnY                                        ',
  '  YccOOnnY                                        ',
  '  YccOOnnY                                        ',
  '  YccOOnnY                                        ',
  '  YYYWYYYY                                        ',
  '  ZuuuuuZZZZ                                      ',
  '  ZuuuuuZ;;Z                                      ',
  '  ZuuuuuQ;;Z                                      ',
  '  ZuuuuuZ;;Z                                      ',
  '  ZZZZZZZZZZ                                      ',
  ],
  things: [
    '                                                  ',
    ' b........e. .............................        ',
    ' .......  .. ..s........................g.        ',
    ' .s..... ... ...........i.....i..h........ ...... ',
    ' ........h.. ... ...f................ .... e.r... ',
    ' ........... ............r................ ...z.. ',
    ' ..3....z... .....h........R.......o...... .g.... ',
    ' ........... ................r............ +..... ',
    ' ......r.... ...........i.....i...f....... ...... ',
    ' ........... ... ..........d......... .... ..r... ',
    ' .U......  . ..............d.......h...... ...... ',
    ' ......+..h. .oo....h......d...........s..        ',
    ' ........... .............e.............+.        ',
    '                    ...                           ',
    '                    .b.               ...         ',
    '                    ...               .+.         ',
    '                                      ...         ',
    '               +..........o.                      ',
    '               ..h.......h.. .................    ',
    '               ............. ...h.............    ',
    '               ... ..... ... ............s....    ',
    '               ............. .................    ',
    '     ......... ............. .....h...e.2.....    ',
    '     .....h.h. ............. .................    ',
    '     ......... ... ..... ... ..........r......    ',
    '     ...       ............. ................. .. ',
    '     .b.       .o...h...z.r. ................. v. ',
    '     ...       ............b ................. .. ',
    '     ...                     .................    ',
    '     ...                     .................    ',
    '                                                  ',
    '                                                  ',
    '     +                                            ',
    '                                                  ',
    '                                                  ',
    '      p                                           ',
    '                                                  ',
    '                                                  ',
    '                                                  ',
    '         e                                        ',
    '      b   a                                       ',
    '                                                  ',
    '                                                  ',
  ],
};
