// LEVEL 2 - "The Foundry"
// A huge open-roofed smelting hall split by a river of lava.
// Yellow keycard -> east wing -> blue keycard -> exit above the catwalk.

export default {
  id: 'foundry',
  name: 'The Foundry',
  subtitle: 'Sector 2 - Smelting Works',
  music: 'foundry',
  parTime: 300,
  fog: { color: 0x160604, near: 4, far: 44 },
  playerAngle: 0,
  defaultWall: '&',
  legend: {
    '.': { floor: 0, ceil: 3.4, light: 0.75, floorTex: 'floor_tile', ceilTex: 'ceil_panel' },
    'l': { floor: 0, ceil: 3.6, light: 1.0, floorTex: 'floor_tile', ceilTex: 'ceil_light' },
    ',': { floor: 0, ceil: 3, light: 0.5, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
    ';': { floor: 0, ceil: 3, light: 0.55, floorTex: 'floor_grate', ceilTex: 'ceil_panel', secret: true },
    'f': { floor: 0, ceil: 10, light: 0.8, floorTex: 'floor_concrete', sky: true },
    '~': { floor: -0.6, ceil: 10, light: 1.1, floorTex: 'lava', sky: true, hazard: 20, lowerTex: 'hellrock' },
    'b': { floor: 0, ceil: 10, light: 0.95, floorTex: 'floor_plate', sky: true, lowerTex: 'support' },
    'c': { floor: 1.6, ceil: 10, light: 0.85, floorTex: 'floor_plate', sky: true, lowerTex: 'support' },
    '6': { floor: 1.2, ceil: 10, light: 0.85, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '5': { floor: 0.8, ceil: 10, light: 0.85, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    '4': { floor: 0.4, ceil: 10, light: 0.85, floorTex: 'floor_plate', sky: true, lowerTex: 'stepside' },
    'k': { floor: 0, ceil: 4, light: 0.55, floorTex: 'floor_grate', ceilTex: 'ceil_rock' },
    'H': { floor: 2.0, ceil: 5, light: 0.65, floorTex: 'floor_plate', ceilTex: 'ceil_panel', lowerTex: 'support' },
    'L': { floor: 0, ceil: 5, light: 0.65, floorTex: 'floor_lift', lift: { low: 0, high: 2.0 } },
    'E': { floor: 1.6, ceil: 4.6, light: 0.7, floorTex: 'floor_hub', ceilTex: 'ceil_panel', lowerTex: 'tech' },
    'X': { floor: 1.6, ceil: 4.6, light: 1.0, floorTex: 'exit', ceilTex: 'ceil_light', exit: true },
    '#': { wall: 'metal' },
    '&': { wall: 'hellrock' },
    '%': { wall: 'brick' },
    'T': { wall: 'tech' },
    'P': { wall: 'support' },
    'C': { wall: 'crate' },
    'D': { door: {}, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'Y': { door: { key: 'yellow' }, floor: 0, ceil: 2.6, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'B': { door: { key: 'blue' }, floor: 1.6, ceil: 4.2, light: 0.6, floorTex: 'floor_plate', ceilTex: 'ceil_panel' },
    'S': { door: { secret: true, tex: 'metal' }, floor: 0, ceil: 3, light: 0.6, floorTex: 'floor_grate', ceilTex: 'ceil_panel' },
  },
  map: [
    '                  TTTTTTTTTTTTT                 ',
    '                  TEEEEXXXEEEET                 ',
    '                  TEEEEXXXEEEET                 ',
    '                  TEEEEEEEEEEET                 ',
    '                  TEEEEEEEEEEET                 ',
    '                  TEEEEEEEEEEET                 ',
    '                  TEEEEEEEEEEET                 ',
    '                  TEEEEEEEEEEET                 ',
    '      &&&&&&&&&&&&&&&&&&B&&&&&&&&&&&&&&&&&&#####',
    '      &fffcccccccccccccccccccccccccccccfff&HHHH#',
    '%%%%%%&fffcccccccccccccccccccccccccccccfff&HHHH#',
    '%kkkkk&fffcccccccccccccccccccccccccccccfff&HHHH#',
    '%kkkkk&ffffffffffffffff666ffffffffffffffff&HHHH#',
    '%kkkkk&fffffffffPffffff555ffffffPfffffffff&.LL.#',
    '%kkkkk&ffffffffffffffff444ffffffffffffffff&....#',
    '%k~~~k&fffffffffffffffffffffffffffffffffff&....#',
    '%k~~~k&~~~~~bb~~~~~~~~~bbb~~~~~~~~bb~~~~~~&....#',
    '%k~~~k&~~~~~bb~~~~~~~~~bbb~~~~~~~~bb~~~~~~&....#',
    '%kkkkk&~~~~~bb~~~~~~~~~bbb~~~~~~~~bb~~~~~~&....#',
    '%kkkkk&fffffffffffffffffffffffffffffffffff&....#',
    '%kkkkkDfffffffffffffffffffffffffffffffffff&...C#',
    '%kkkkk&fffPfffffffffffffffffffffffffffPfff&...C#',
    '%CCkkk&fffffffffffffffffffffffffffffffffffY....#',
    '%CCkkk&fffffffffffffffffffffffffffffffffff&....#',
    '%kkkkk&fffffffffPfffffffffffffffPfffffffff&....#',
    '%kkkkk&fffffffffffffffffffffffffffffffffff&....#',
    '%%%%%%&fffffffffffffffffffffffffffffffffff&....#',
    '      &&&&&&&&&&&&&&&&#,,,#&&&&&&&&&&&&&&&&#####',
    '                      #,,,#                     ',
    '                      #,,,#                     ',
    '                      #,,,#                     ',
    '                      #,,,#                     ',
    '                    ####D####                   ',
    '                #####.......#                   ',
    '                #;;;#..lll..#                   ',
    '                #;;;S..lll..#                   ',
    '                #;;;#..lll..#                   ',
    '                #####.......#                   ',
    '                    #.......#                   ',
    '                    #########                   ',
  ],
  things: [
    '                                                ',
    '                   +.........c                  ',
    '                   ...........                  ',
    '                   .g.......g.                  ',
    '                   .....w.....                  ',
    '                   ...........                  ',
    '                   ...r...r...                  ',
    '                   ...........                  ',
    '                                                ',
    '       .t...............................t. .... ',
    '       .....c..w........*...f.4.c.w....... v.U. ',
    ' ....* ................................... .... ',
    ' .Y... ................................... .... ',
    ' ..z.. ......... ............... ......... .... ',
    ' ..... .............g.........g.......e... .... ',
    ' ..... ................................... .... ',
    ' ..... ................................... ..r. ',
    ' ..... ................................... .... ',
    ' s.... ................................... w... ',
    ' ..... .b................................. .... ',
    ' ..g.. .......r.........e........o..z..... .z.  ',
    ' ..... ... .......oo..........h....... ... ...  ',
    '   ... .....h.....f....................... .... ',
    '   ... .....................s............. .... ',
    ' ...g. ......... ...h.........f. ......... .r.. ',
    ' E.... ..s..........................r...+. .... ',
    '       .t...............................t. +..c ',
    '                       ...                      ',
    '                       ...                      ',
    '                       .h.                      ',
    '                       b..                      ',
    '                       ...                      ',
    '                                                ',
    '                     .......                    ',
    '                 K.. .e...+.                    ',
    '                 .5. .......                    ',
    '                 ..a .......                    ',
    '                     ...p...                    ',
    '                     .......                    ',
    '                                                ',
  ],
};
